import { Company, CompanySize, FiscalData } from '@/types';
import { calculateFinancialCapacity } from './estimators';

export const BRAZILIAN_STATES = [
  { code: 'AC', name: 'Acre' },
  { code: 'AL', name: 'Alagoas' },
  { code: 'AP', name: 'Amapá' },
  { code: 'AM', name: 'Amazonas' },
  { code: 'BA', name: 'Bahia' },
  { code: 'CE', name: 'Ceará' },
  { code: 'DF', name: 'Distrito Federal' },
  { code: 'ES', name: 'Espírito Santo' },
  { code: 'GO', name: 'Goiás' },
  { code: 'MA', name: 'Maranhão' },
  { code: 'MT', name: 'Mato Grosso' },
  { code: 'MS', name: 'Mato Grosso do Sul' },
  { code: 'MG', name: 'Minas Gerais' },
  { code: 'PA', name: 'Pará' },
  { code: 'PB', name: 'Paraíba' },
  { code: 'PR', name: 'Paraná' },
  { code: 'PE', name: 'Pernambuco' },
  { code: 'PI', name: 'Piauí' },
  { code: 'RJ', name: 'Rio de Janeiro' },
  { code: 'RN', name: 'Rio Grande do Norte' },
  { code: 'RS', name: 'Rio Grande do Sul' },
  { code: 'RO', name: 'Rondônia' },
  { code: 'RR', name: 'Roraima' },
  { code: 'SC', name: 'Santa Catarina' },
  { code: 'SP', name: 'São Paulo' },
  { code: 'SE', name: 'Sergipe' },
  { code: 'TO', name: 'Tocantins' },
];

export const CNAE_SECTORS = [
  { code: '62.01-5-01', desc: 'Desenvolvimento de programas de computador sob encomenda (TI)' },
  { code: '62.02-3-00', desc: 'Desenvolvimento e licenciamento de programas de computador customizáveis' },
  { code: '62.09-1-00', desc: 'Suporte técnico, manutenção e outros serviços em tecnologia da informação' },
  { code: '41.20-4-00', desc: 'Construção de edifícios e obras de infraestrutura civil' },
  { code: '71.12-0-00', desc: 'Serviços de engenharia e consultoria técnica' },
  { code: '86.10-1-01', desc: 'Atividades de atendimento hospitalar e serviços médicos' },
  { code: '46.45-1-01', desc: 'Comércio atacadista de instrumentos e materiais para uso médico-hospitalar' },
  { code: '70.20-4-00', desc: 'Atividades de consultoria em gestão empresarial' },
  { code: '49.30-2-02', desc: 'Transporte rodoviário de carga intermunicipal e interestadual' },
  { code: '56.20-1-01', desc: 'Fornecimento de alimentos preparados preponderantemente para empresas' },
  { code: '80.11-1-01', desc: 'Atividades de vigilância e segurança privada' },
  { code: '81.21-4-00', desc: 'Limpeza em prédios e em domicílios' },
];

export const INITIAL_COMPANIES_RAW: Array<Omit<Company, 'financialIndicators' | 'fiscalData'>> = [
  // ==========================================
  // 1. MEIs (Microempreendedores Individuais)
  // ==========================================
  {
    id: 'mei-rn-01',
    cnpj: '48912304000188',
    legalName: 'LUCAS MEDEIROS ENGENHARIA E LAUDOS PERICIAIS',
    tradeName: 'Lucas Medeiros Engenharia & Perícias',
    status: 'ATIVA',
    registrationDate: '2021-06-15',
    primaryCnaeCode: '71.12-0-00',
    primaryCnaeDesc: 'Serviços de engenharia e consultoria técnica',
    secondaryCnaes: [
      { code: '41.20-4-00', desc: 'Construção de edifícios e reformas' },
      { code: '71.19-7-03', desc: 'Serviços de desenho técnico' },
    ],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 45000,
    state: 'RN',
    city: 'Natal',
    neighborhood: 'Ponta Negra',
    zipCode: '59090-100',
    street: 'Rua das Conchas',
    number: '104',
    email: 'lucas.eng.laudos@gmail.com',
    phone: '(84) 98844-1234',
    partners: [{ id: 'part-mei-01', name: 'Lucas Gabriel de Medeiros', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-01',
        companyId: 'mei-rn-01',
        contractNumber: '018/2024-SEMURB',
        buyerAgency: 'Secretaria Municipal de Meio Ambiente e Urbanismo (SEMURB-Natal)',
        buyerUf: 'RN',
        modality: 'Dispensa de Licitação',
        object: 'Elaboração de laudos periciais estruturais e vistorias de acessibilidade.',
        category: 'Engenharia & Obras',
        totalValue: 48000,
        startDate: '2024-03-01',
        endDate: '2024-12-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-rn-02',
    cnpj: '45889102000133',
    legalName: 'ANA BEATRIZ SILVA DESENVOLVIMENTO WEB E DESIGN',
    tradeName: 'Bia Tech & Web Design',
    status: 'ATIVA',
    registrationDate: '2022-01-18',
    primaryCnaeCode: '62.01-5-01',
    primaryCnaeDesc: 'Desenvolvimento de programas de computador sob encomenda (TI)',
    secondaryCnaes: [
      { code: '62.09-1-00', desc: 'Suporte técnico em tecnologia da informação' },
    ],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 30000,
    state: 'RN',
    city: 'Mossoró',
    neighborhood: 'Nova Betânia',
    zipCode: '59612-000',
    street: 'Rua das Camélias',
    number: '88',
    email: 'ana.beatriz.tech@outlook.com',
    phone: '(84) 99122-3344',
    partners: [{ id: 'part-mei-02', name: 'Ana Beatriz da Silva', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-02',
        companyId: 'mei-rn-02',
        contractNumber: '045/2024-PMM',
        buyerAgency: 'Prefeitura Municipal de Mossoró',
        buyerUf: 'RN',
        modality: 'Dispensa de Licitação',
        object: 'Desenvolvimento de hotsite comemorativo e landing pages de eventos municipais.',
        category: 'TI & Software',
        totalValue: 35000,
        startDate: '2024-04-01',
        endDate: '2024-10-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-sp-01',
    cnpj: '41203490000122',
    legalName: 'ROBERTO ALVES CONSULTORIA EMPRESARIAL',
    tradeName: 'Alves Gestão & Finanças MEI',
    status: 'ATIVA',
    registrationDate: '2021-08-10',
    primaryCnaeCode: '70.20-4-00',
    primaryCnaeDesc: 'Atividades de consultoria em gestão empresarial',
    secondaryCnaes: [{ code: '85.99-6-04', desc: 'Treinamento gerencial' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 25000,
    state: 'SP',
    city: 'São Paulo',
    neighborhood: 'Pinheiros',
    zipCode: '05422-000',
    street: 'Rua Fradique Coutinho',
    number: '310',
    email: 'roberto.alves.consultor@gmail.com',
    phone: '(11) 98765-4321',
    partners: [{ id: 'part-mei-03', name: 'Roberto Alves de Almeida', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-03',
        companyId: 'mei-sp-01',
        contractNumber: '089/2024-FAPESP',
        buyerAgency: 'Fundação de Amparo à Pesquisa do Estado de SP (FAPESP)',
        buyerUf: 'SP',
        modality: 'Dispensa de Licitação',
        object: 'Consultoria e assessoria técnica em análise de viabilidade de projetos de inovação.',
        category: 'Consultoria & Treinamento',
        totalValue: 52000,
        startDate: '2024-02-01',
        endDate: '2024-11-30',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-rj-01',
    cnpj: '39871234000109',
    legalName: 'FELIPE CARVALHO SUPORTE DE TI E INFRAESTRUTURA',
    tradeName: 'FC Tech Suporte',
    status: 'ATIVA',
    registrationDate: '2020-11-05',
    primaryCnaeCode: '62.09-1-00',
    primaryCnaeDesc: 'Suporte técnico, manutenção e outros serviços em tecnologia da informação',
    secondaryCnaes: [{ code: '62.01-5-01', desc: 'Desenvolvimento de programas de computador sob encomenda (TI)' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 20000,
    state: 'RJ',
    city: 'Rio de Janeiro',
    neighborhood: 'Tijuca',
    zipCode: '20511-000',
    street: 'Rua Conde de Bonfim',
    number: '420',
    email: 'felipe.fctech@gmail.com',
    phone: '(21) 97654-3210',
    partners: [{ id: 'part-mei-04', name: 'Felipe Carvalho Guimarães', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-04',
        companyId: 'mei-rj-01',
        contractNumber: '033/2024-UERJ',
        buyerAgency: 'Universidade do Estado do Rio de Janeiro (UERJ)',
        buyerUf: 'RJ',
        modality: 'Dispensa de Licitação',
        object: 'Manutenção preventiva e corretiva de equipamentos de informática.',
        category: 'TI & Software',
        totalValue: 42000,
        startDate: '2024-01-15',
        endDate: '2024-12-15',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-ce-01',
    cnpj: '42198765000177',
    legalName: 'MARCOS VINICIUS SERVICOS DE ENGENHARIA E LAUDOS',
    tradeName: 'MV Engenharia & Inspeções',
    status: 'ATIVA',
    registrationDate: '2021-04-12',
    primaryCnaeCode: '71.12-0-00',
    primaryCnaeDesc: 'Serviços de engenharia e consultoria técnica',
    secondaryCnaes: [{ code: '71.19-7-03', desc: 'Desenho técnico e vistorias' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 35000,
    state: 'CE',
    city: 'Fortaleza',
    neighborhood: 'Meireles',
    zipCode: '60165-080',
    street: 'Rua Pereira Valente',
    number: '750',
    email: 'marcos.eng.ce@gmail.com',
    phone: '(85) 98811-2233',
    partners: [{ id: 'part-mei-05', name: 'Marcos Vinicius de Souza', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-05',
        companyId: 'mei-ce-01',
        contractNumber: '071/2024-SEJUS-CE',
        buyerAgency: 'Secretaria da Administração Penitenciária do Ceará',
        buyerUf: 'CE',
        modality: 'Dispensa de Licitação',
        object: 'Inspeções técnicas e laudos de engenharia predial.',
        category: 'Engenharia & Obras',
        totalValue: 56000,
        startDate: '2024-03-10',
        endDate: '2024-12-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-pb-01',
    cnpj: '47890123000144',
    legalName: 'JULIANA PEREIRA SERVICOS DE ALIMENTACAO E BUFFET',
    tradeName: 'Sabor Nordestino Eventos MEI',
    status: 'ATIVA',
    registrationDate: '2022-03-01',
    primaryCnaeCode: '56.20-1-01',
    primaryCnaeDesc: 'Fornecimento de alimentos preparados preponderantemente para empresas',
    secondaryCnaes: [{ code: '56.20-1-02', desc: 'Serviços de alimentação para eventos' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 20000,
    state: 'PB',
    city: 'Campina Grande',
    neighborhood: 'Catolé',
    zipCode: '58410-000',
    street: 'Av. Elpídio de Almeida',
    number: '1100',
    email: 'juliana.sabornordestino@gmail.com',
    phone: '(83) 98777-6655',
    partners: [{ id: 'part-mei-06', name: 'Juliana Pereira Nóbrega', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-06',
        companyId: 'mei-pb-01',
        contractNumber: '015/2024-UEPB',
        buyerAgency: 'Universidade Estadual da Paraíba (UEPB)',
        buyerUf: 'PB',
        modality: 'Dispensa de Licitação',
        object: 'Fornecimento de coffee break e kits lanche para simpósios acadêmicos.',
        category: 'Alimentação & Logística',
        totalValue: 38000,
        startDate: '2024-02-15',
        endDate: '2024-11-30',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-mg-01',
    cnpj: '44102938000199',
    legalName: 'THIAGO SILVA MANUTENCAO ELETRICA E PREDIAL',
    tradeName: 'TS Manutenções & Engenharia',
    status: 'ATIVA',
    registrationDate: '2020-07-25',
    primaryCnaeCode: '71.12-0-00',
    primaryCnaeDesc: 'Serviços de engenharia e consultoria técnica',
    secondaryCnaes: [{ code: '43.21-5-00', desc: 'Instalação e manutenção elétrica' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 40000,
    state: 'MG',
    city: 'Belo Horizonte',
    neighborhood: 'Savassi',
    zipCode: '30140-000',
    street: 'Rua Pernambuco',
    number: '500',
    email: 'thiago.eletrica.bh@gmail.com',
    phone: '(31) 98833-4455',
    partners: [{ id: 'part-mei-07', name: 'Thiago Silva Santos', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-07',
        companyId: 'mei-mg-01',
        contractNumber: '062/2024-UFMG',
        buyerAgency: 'Universidade Federal de Minas Gerais (UFMG)',
        buyerUf: 'MG',
        modality: 'Dispensa de Licitação',
        object: 'Manutenção elétrica preventiva e adequação de quadros de comando nos laboratórios.',
        category: 'Engenharia & Obras',
        totalValue: 64000,
        startDate: '2024-01-20',
        endDate: '2024-12-20',
        status: 'VIGENTE',
        sourceSystem: 'Compras.gov.br',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-ba-01',
    cnpj: '46781290000111',
    legalName: 'CAROLINA SANTOS DESIGN E COMUNICACAO DIGITAL',
    tradeName: 'Carol Santos Studio Digital',
    status: 'ATIVA',
    registrationDate: '2021-09-14',
    primaryCnaeCode: '62.01-5-01',
    primaryCnaeDesc: 'Desenvolvimento de programas de computador sob encomenda (TI)',
    secondaryCnaes: [{ code: '70.20-4-00', desc: 'Atividades de consultoria em gestão empresarial' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 28000,
    state: 'BA',
    city: 'Salvador',
    neighborhood: 'Rio Vermelho',
    zipCode: '41940-000',
    street: 'Rua Odilon Santos',
    number: '205',
    email: 'carol.studio.ba@gmail.com',
    phone: '(71) 99188-7766',
    partners: [{ id: 'part-mei-08', name: 'Carolina Santos Santana', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-08',
        companyId: 'mei-ba-01',
        contractNumber: '028/2024-FGM',
        buyerAgency: 'Fundação Gregório de Mattos / Salvador',
        buyerUf: 'BA',
        modality: 'Dispensa de Licitação',
        object: 'Identidade visual e desenvolvimento de portal de editais culturais.',
        category: 'TI & Software',
        totalValue: 46000,
        startDate: '2024-03-01',
        endDate: '2024-10-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-rs-01',
    cnpj: '49123847000166',
    legalName: 'GABRIEL ZIMMERMANN CONSULTORIA EM TI',
    tradeName: 'Zimmermann Cloud & DevOps MEI',
    status: 'ATIVA',
    registrationDate: '2021-10-10',
    primaryCnaeCode: '62.01-5-01',
    primaryCnaeDesc: 'Desenvolvimento de programas de computador sob encomenda (TI)',
    secondaryCnaes: [{ code: '62.02-3-00', desc: 'Desenvolvimento e licenciamento de softwares' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 32000,
    state: 'RS',
    city: 'Porto Alegre',
    neighborhood: 'Moinhos de Vento',
    zipCode: '90570-020',
    street: 'Rua Padre Chagas',
    number: '300',
    email: 'gabriel.zimmermann.ti@gmail.com',
    phone: '(51) 98111-9988',
    partners: [{ id: 'part-mei-09', name: 'Gabriel Zimmermann', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-09',
        companyId: 'mei-rs-01',
        contractNumber: '019/2024-PROCERGS',
        buyerAgency: 'Centro de Tecnologia da Informação do RS (PROCERGS)',
        buyerUf: 'RS',
        modality: 'Dispensa de Licitação',
        object: 'Suporte técnico especializado em automação de esteiras CI/CD e containers.',
        category: 'TI & Software',
        totalValue: 54000,
        startDate: '2024-02-01',
        endDate: '2024-12-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'mei-sc-01',
    cnpj: '43908123000155',
    legalName: 'RENATA SOUZA CONSULTORIA AMBIENTAL E LAUDOS',
    tradeName: 'Renata Souza Engenharia Ambiental',
    status: 'ATIVA',
    registrationDate: '2022-02-14',
    primaryCnaeCode: '71.12-0-00',
    primaryCnaeDesc: 'Serviços de engenharia e consultoria técnica',
    secondaryCnaes: [{ code: '74.90-1-04', desc: 'Atividades de intermediação e agenciamento' }],
    legalNature: '213-5 - Empresário Individual',
    companySize: 'MEI',
    shareCapital: 30000,
    state: 'SC',
    city: 'Florianópolis',
    neighborhood: 'Itacorubi',
    zipCode: '88034-000',
    street: 'Rodovia Amaro Antônio Vieira',
    number: '140',
    email: 'renata.ambiental.sc@gmail.com',
    phone: '(48) 99199-8877',
    partners: [{ id: 'part-mei-10', name: 'Renata Souza Silveira', role: 'Titular / MEI' }],
    publicContracts: [
      {
        id: 'cont-mei-10',
        companyId: 'mei-sc-01',
        contractNumber: '037/2024-IMA-SC',
        buyerAgency: 'Instituto do Meio Ambiente de Santa Catarina (IMA-SC)',
        buyerUf: 'SC',
        modality: 'Dispensa de Licitação',
        object: 'Elaboração de estudos de impacto de vizinhança e laudos ambientais.',
        category: 'Engenharia & Obras',
        totalValue: 49000,
        startDate: '2024-03-15',
        endDate: '2024-11-30',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },

  // ==========================================
  // 2. Microempresas (ME)
  // ==========================================
  {
    id: 'me-rn-01',
    cnpj: '31567890000144',
    legalName: 'GEOESTRUTURA ENGENHARIA E CONSULTORIA TECNICA LTDA',
    tradeName: 'GeoEstrutura Projetos & Sondagens',
    status: 'ATIVA',
    registrationDate: '2019-07-10',
    primaryCnaeCode: '71.12-0-00',
    primaryCnaeDesc: 'Serviços de engenharia e consultoria técnica',
    secondaryCnaes: [
      { code: '71.19-7-01', desc: 'Serviços de topografia e geodésia' },
      { code: '43.13-4-00', desc: 'Obras de terraplenagem' },
    ],
    legalNature: '206-2 - Sociedade Empresária Limitada',
    companySize: 'ME',
    shareCapital: 250000,
    state: 'RN',
    city: 'Parnamirim',
    neighborhood: 'Centro',
    zipCode: '59140-000',
    street: 'Av. Tenente Medeiros',
    number: '450',
    email: 'comercial@geoestrutura.com.br',
    phone: '(84) 3272-9900',
    partners: [{ id: 'part-rn-01', name: 'Fernando Henrique Câmara', role: 'Sócio-Administrador' }],
    publicContracts: [
      {
        id: 'cont-geo-01',
        companyId: 'me-rn-01',
        contractNumber: '041/2023-SIN',
        buyerAgency: 'Secretaria de Estado da Infraestrutura do RN (SIN-RN)',
        buyerUf: 'RN',
        modality: 'Tomada de Preços',
        object: 'Serviços de topografia e sondagem geotécnica para rodovias estaduais.',
        category: 'Engenharia & Obras',
        totalValue: 320000,
        startDate: '2023-09-01',
        endDate: '2025-03-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-09-18T10:00:00Z',
  },
  {
    id: 'me-sp-01',
    cnpj: '24987654000188',
    legalName: 'ALPHA CONSULTORIA E GESTAO ESTRATEGICA LTDA',
    tradeName: 'Alpha Advisory & Data',
    status: 'ATIVA',
    registrationDate: '2020-03-10',
    primaryCnaeCode: '70.20-4-00',
    primaryCnaeDesc: 'Atividades de consultoria em gestão empresarial',
    secondaryCnaes: [
      { code: '85.99-6-04', desc: 'Treinamento gerencial' },
      { code: '71.12-0-00', desc: 'Serviços de engenharia e consultoria técnica' },
    ],
    legalNature: '206-2 - Sociedade Empresária Limitada',
    companySize: 'ME',
    shareCapital: 150000,
    state: 'SP',
    city: 'São Paulo',
    neighborhood: 'Itaim Bibi',
    zipCode: '04538-132',
    street: 'Rua Funchal',
    number: '418',
    email: 'contato@alphaadvisory.com.br',
    phone: '(11) 4003-8899',
    partners: [{ id: 'part-08', name: 'Marcelo Telles Guimarães', role: 'Sócio-Administrador' }],
    publicContracts: [
      {
        id: 'cont-07',
        companyId: 'me-sp-01',
        contractNumber: '044/2024-ENAP',
        buyerAgency: 'Escola Nacional de Administração Pública (ENAP)',
        buyerUf: 'DF',
        modality: 'Pregão Eletrônico',
        object: 'Consultoria técnica para governança digital.',
        category: 'Consultoria & Treinamento',
        totalValue: 620000,
        startDate: '2024-04-01',
        endDate: '2025-03-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-03-05T09:00:00Z',
    updatedAt: '2024-09-12T11:45:00Z',
  },

  // ==========================================
  // 3. Empresas de Pequeno Porte (EPP)
  // ==========================================
  {
    id: 'epp-rn-01',
    cnpj: '08453912000140',
    legalName: 'POTIGUAR TECH SOLUCOES DIGITAIS LTDA',
    tradeName: 'Potiguar Tech Cloud & AI',
    status: 'ATIVA',
    registrationDate: '2018-04-12',
    primaryCnaeCode: '62.01-5-01',
    primaryCnaeDesc: 'Desenvolvimento de programas de computador sob encomenda (TI)',
    secondaryCnaes: [
      { code: '62.02-3-00', desc: 'Desenvolvimento e licenciamento de softwares' },
      { code: '71.12-0-00', desc: 'Serviços de engenharia e consultoria técnica' },
    ],
    legalNature: '206-2 - Sociedade Empresária Limitada',
    companySize: 'EPP',
    shareCapital: 850000,
    state: 'RN',
    city: 'Natal',
    neighborhood: 'Candelária',
    zipCode: '59065-100',
    street: 'Av. Salgado Filho',
    number: '1420',
    email: 'contato@potiguartech.com.br',
    phone: '(84) 3211-4090',
    partners: [
      { id: 'part-01', name: 'Carlos Eduardo Bezerra da Rocha', role: 'Sócio-Administrador' },
      { id: 'part-02', name: 'Mariana Silveira Furtado', role: 'Sócia' },
    ],
    publicContracts: [
      {
        id: 'cont-01',
        companyId: 'epp-rn-01',
        contractNumber: '142/2023-SEPLAN',
        buyerAgency: 'Governo do Estado do Rio Grande do Norte (SEPLAN-RN)',
        buyerUf: 'RN',
        modality: 'Pregão Eletrônico',
        object: 'Modernização e cloud modernization para sistemas fiscais estaduais.',
        category: 'TI & Software',
        totalValue: 3420000,
        startDate: '2023-06-01',
        endDate: '2025-05-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-09-15T14:30:00Z',
  },

  // ==========================================
  // 4. Médio Porte
  // ==========================================
  {
    id: 'medio-ce-01',
    cnpj: '33182904000105',
    legalName: 'BIOTEC MED DISTRIBUIDORA DE MEDICAMENTOS E MATERIAIS LTDA',
    tradeName: 'BioTec Hospitalar',
    status: 'ATIVA',
    registrationDate: '2016-11-04',
    primaryCnaeCode: '46.45-1-01',
    primaryCnaeDesc: 'Comércio atacadista de instrumentos e materiais para uso médico-hospitalar',
    secondaryCnaes: [{ code: '46.44-3-01', desc: 'Comércio de medicamentos' }],
    legalNature: '206-2 - Sociedade Empresária Limitada',
    companySize: 'MEDIO',
    shareCapital: 3200000,
    state: 'CE',
    city: 'Fortaleza',
    neighborhood: 'Aldeota',
    zipCode: '60150-160',
    street: 'Av. Santos Dumont',
    number: '2800',
    email: 'licitacoes@biotechosp.com.br',
    phone: '(85) 3450-9200',
    partners: [{ id: 'part-06', name: 'Dr. Leonardo Aguiar Parente', role: 'Sócio-Administrador' }],
    publicContracts: [
      {
        id: 'cont-05',
        companyId: 'medio-ce-01',
        contractNumber: '320/2023-SESA-CE',
        buyerAgency: 'Secretaria da Saúde do Estado do Ceará (SESA-CE)',
        buyerUf: 'CE',
        modality: 'Ata de Registro de Preços',
        object: 'Fornecimento contínuo de kits cirúrgicos e insumos descartáveis.',
        category: 'Saúde & Medicamentos',
        totalValue: 9800000,
        startDate: '2023-08-01',
        endDate: '2025-07-31',
        status: 'VIGENTE',
        sourceSystem: 'PNCP',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-01T14:00:00Z',
    updatedAt: '2024-09-10T16:20:00Z',
  },
  {
    id: 'medio-rn-01',
    cnpj: '11345678000155',
    legalName: 'SERVICOS INTEGRADOS GUARDA REAL DE VIGILANCIA LTDA',
    tradeName: 'Guarda Real Segurança & Facilities',
    status: 'ATIVA',
    registrationDate: '2015-05-18',
    primaryCnaeCode: '80.11-1-01',
    primaryCnaeDesc: 'Atividades de vigilância e segurança privada',
    secondaryCnaes: [{ code: '81.21-4-00', desc: 'Limpeza em prédios e em domicílios' }],
    legalNature: '206-2 - Sociedade Empresária Limitada',
    companySize: 'MEDIO',
    shareCapital: 2000000,
    state: 'RN',
    city: 'Parnamirim',
    neighborhood: 'Nova Parnamirim',
    zipCode: '59150-000',
    street: 'Av. Maria Lacerda Montenegro',
    number: '890',
    email: 'comercial@guardareal.com.br',
    phone: '(84) 3644-1234',
    partners: [{ id: 'part-09', name: 'Antonio Marcos Pinheiro', role: 'Sócio-Administrador' }],
    publicContracts: [
      {
        id: 'cont-08',
        companyId: 'medio-rn-01',
        contractNumber: '110/2023-UFRN',
        buyerAgency: 'Universidade Federal do Rio Grande do Norte (UFRN)',
        buyerUf: 'RN',
        modality: 'Pregão Eletrônico',
        object: 'Vigilância armada e desarmada para os campi universitários.',
        category: 'Serviços Terceirizados',
        totalValue: 18450000,
        startDate: '2023-01-01',
        endDate: '2025-12-31',
        status: 'VIGENTE',
        sourceSystem: 'Compras.gov.br',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-09-18T08:00:00Z',
  },

  // ==========================================
  // 5. Grande Porte
  // ==========================================
  {
    id: 'grande-rn-01',
    cnpj: '19874213000192',
    legalName: 'NORDESTE ENGENHARIA E INFRAESTRUTURA SUSTENTAVEL S.A.',
    tradeName: 'Nordeste Infra & Construções',
    status: 'ATIVA',
    registrationDate: '2012-08-20',
    primaryCnaeCode: '41.20-4-00',
    primaryCnaeDesc: 'Construção de edifícios e obras de infraestrutura civil',
    secondaryCnaes: [
      { code: '71.12-0-00', desc: 'Serviços de engenharia e consultoria técnica' },
      { code: '42.11-1-01', desc: 'Construção de rodovias e ferrovias' },
    ],
    legalNature: '205-4 - Sociedade Anônima Fechada',
    companySize: 'GRANDE',
    shareCapital: 12500000,
    state: 'RN',
    city: 'Mossoró',
    neighborhood: 'Abolição',
    zipCode: '59618-000',
    street: 'Rua Alberto Maranhão',
    number: '310',
    email: 'diretoria@nordesteinfra.eng.br',
    phone: '(84) 3315-8800',
    partners: [{ id: 'part-03', name: 'Rodrigo Medeiros Alencar', role: 'Diretor Presidente' }],
    publicContracts: [
      {
        id: 'cont-03',
        companyId: 'grande-rn-01',
        contractNumber: '502/2022-DNIT',
        buyerAgency: 'Departamento Nacional de Infraestrutura de Transportes (DNIT)',
        buyerUf: 'DF',
        modality: 'Concorrência Pública',
        object: 'Execução de obras de duplicação, restauração e pavimentação na BR-304/RN.',
        category: 'Engenharia & Obras',
        totalValue: 48900000,
        startDate: '2022-10-01',
        endDate: '2025-12-31',
        status: 'VIGENTE',
        sourceSystem: 'Compras.gov.br',
      },
    ],
    hasPublicContracts: true,
  totalContractsVolume: 0,
  activeContractsCount: 0,
  capacityScore: 65,
  createdAt: '2024-01-12T11:00:00Z',
    updatedAt: '2024-09-17T09:15:00Z',
  },
];

function generateFiscalData(c: Omit<Company, 'financialIndicators' | 'fiscalData'>): FiscalData {
  const isMei = c.companySize === 'MEI';
  const isMeOrEpp = c.companySize === 'ME' || c.companySize === 'EPP';
  const isMedio = c.companySize === 'MEDIO';
  const isGrande = c.companySize === 'GRANDE';

  let employeeCount = 1;
  let payrollMonthly = 1412;
  let regime: FiscalData['taxRegime'] = 'MEI';
  let regimeDesc = 'SIMEI - Sistema de Recolhimento em Valores Fixos Mensais dos Tributos do Simples Nacional (MEI)';

  if (isMei) {
    employeeCount = 1; // Limite legal do MEI
    payrollMonthly = 1600;
    regime = 'MEI';
    regimeDesc = 'Optante pelo SIMEI (MEI - Limite R$ 81.000/ano)';
  } else if (c.companySize === 'ME') {
    employeeCount = 6;
    payrollMonthly = 18500;
    regime = 'SIMPLES_NACIONAL';
    regimeDesc = 'Simples Nacional (Microempresa - Limite R$ 360.000/ano)';
  } else if (c.companySize === 'EPP') {
    employeeCount = 28;
    payrollMonthly = 85000;
    regime = 'SIMPLES_NACIONAL';
    regimeDesc = 'Simples Nacional (Empresa de Pequeno Porte - Limite R$ 4.800.000/ano)';
  } else if (isMedio) {
    employeeCount = 110;
    payrollMonthly = 380000;
    regime = 'LUCRO_PRESUMIDO';
    regimeDesc = 'Lucro Presumido (Apuração Trimestral IRPJ/CSLL)';
  } else if (isGrande) {
    employeeCount = 640;
    payrollMonthly = 2450000;
    regime = 'LUCRO_REAL';
    regimeDesc = 'Lucro Real (Obrigatório para faturamento > R$ 78M)';
  }

  const optDate = c.registrationDate ? `${c.registrationDate.slice(0, 4)}-01-01` : '2021-01-01';

  return {
    taxRegime: regime,
    taxRegimeDescription: regimeDesc,
    isSimplesNacional: isMei || isMeOrEpp,
    simplesOptInDate: isMei || isMeOrEpp ? optDate : undefined,
    isSimei: isMei,
    simeiOptInDate: isMei ? optDate : undefined,
    federalTaxDebtStatus: 'REGULAR',
    cndFederal: 'VÁLIDA / EMITIDA',
    cndFgts: 'REGULAR (CRF ATIVO)',
    cndTrabalhista: 'CERTIDÃO NEGATIVA (CNDT VÁLIDA)',
    stateRegistration: `20.${c.cnpj.slice(2, 5)}.${c.cnpj.slice(5, 8)}-${c.cnpj.slice(8, 9)}`,
    municipalRegistration: `${c.cnpj.slice(0, 6)}/001`,
    employeeCountDeclared: employeeCount,
    employeeRangeDescription: `${employeeCount} funcionário(s) registrado(s) no eSocial/CAGED`,
    estimatedPayrollMonthly: payrollMonthly,
    dasnStatus: isMei ? 'ENTREGUE / REGULAR' : undefined,
  };
}

export const INITIAL_COMPANIES: Company[] = INITIAL_COMPANIES_RAW.map((c) => {
  const activeContractsAnnualSum = c.publicContracts
    .filter((pc) => pc.status === 'VIGENTE')
    .reduce((acc, curr) => acc + curr.totalValue, 0);

  const indicators = calculateFinancialCapacity({
    companySize: c.companySize,
    shareCapital: c.shareCapital,
    activePublicContractsAnnualSum: activeContractsAnnualSum,
    primaryCnaeCode: c.primaryCnaeCode,
    taxRegime:
      c.companySize === 'MEI'
        ? 'MEI'
        : c.companySize === 'ME' || c.companySize === 'EPP'
        ? 'SIMPLES_NACIONAL'
        : c.companySize === 'MEDIO'
        ? 'LUCRO_PRESUMIDO'
        : 'LUCRO_REAL',
  });

  const fiscal = generateFiscalData(c);

  return {
    ...c,
    fiscalData: fiscal,
    financialIndicators: {
      id: `ind-${c.id}`,
      companyId: c.id,
      calculatedAt: new Date().toISOString(),
      ...indicators,
    },
  };
});
